
package ru.javarush.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import net.java.dev.jaxb.array.ObjectFactory;
import net.java.dev.jaxb.array.StringArray;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Library", targetNamespace = "http://ws.javarush.ru/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Library {


    /**
     * 
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.javarush.ru/Library/getBooksListRequest", output = "http://ws.javarush.ru/Library/getBooksListResponse")
    public StringArray getBooksList();

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.javarush.ru/Library/getBookRequest", output = "http://ws.javarush.ru/Library/getBookResponse")
    public byte[] getBook(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
